name: PowerShell to EXE 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install PS2EXE
      run: |
        Install-Module -Name PS2EXE -Force -AllowClobber -Scope CurrentUser
          
    - name: Convert PowerShell Script to EXE
      run: |
        Invoke-ps2exe mtuFragmentation.ps1 script.exe

    - name: Create GitHub Release 
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.sha }}
        release_name: v${{ github.sha }}
        files: |
          script.exe
          taskSchedularPIA.ps1
